### ISSUE TITLE
`python manage.py syncdb` fails in ubuntu 14.04 VM

### ISSUE THREAD

**Issue by patcon** [HumanDynamics/openPDS#46]
```
(pdsEnv)kitchen@60aa1b8653be:~/pdsEnv/openPDS$ python start.py 


##########################################################################
NOTE: This must be run from the root directory of the openPDS project
and for the virtualenv to be located in the directory above it.
ie: you should be in /pdsEnv/openPDS
if necessary, press ctrl+c to exit and then move to the correct directory.
##########################################################################
Enter the path to the openPDS virtual environment (or nothing for default: /home/kitchen/pdsEnv): 

Enter the Registry Server domain name (or nothing for MIT default: linkedpersonaldata.org): 

Which backend would you like to use for personal data storage?
1. MongoDB (openpds.backends.mongo)
2. SQLite (openpds.backends.sqlite)
3. Postsgres (openpds.backends.postgres)
Enter 1, 2, or 3 (default is 1): 
wsgi.py and settings.py generated
Setup done. Please continue with django setup by running: ./manage.py syncdb
Make sure that the user running your server process (www-data for apache, for example) has write access to all directories from your PDS virtual env to the openpds package directory
Finally, after running syncdb, provide the user running the server process with write access to the test.db file generated in the openpds directory
(pdsEnv)kitchen@60aa1b8653be:~/pdsEnv/openPDS$ ./manage.py syncdb
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/kitchen/pdsEnv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/home/kitchen/pdsEnv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/kitchen/pdsEnv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 261, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/kitchen/pdsEnv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 69, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/home/kitchen/pdsEnv/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/kitchen/pdsEnv/local/lib/python2.7/site-packages/django/core/management/commands/syncdb.py", line 8, in <module>
    from django.core.management.sql import custom_sql_for_model, emit_post_sync_signal
  File "/home/kitchen/pdsEnv/local/lib/python2.7/site-packages/django/core/management/sql.py", line 6, in <module>
    from django.db import models
  File "/home/kitchen/pdsEnv/local/lib/python2.7/site-packages/django/db/__init__.py", line 11, in <module>
    if DEFAULT_DB_ALIAS not in settings.DATABASES:
  File "/home/kitchen/pdsEnv/local/lib/python2.7/site-packages/django/utils/functional.py", line 184, in inner
    self._setup()
  File "/home/kitchen/pdsEnv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/kitchen/pdsEnv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 95, in __init__
    raise ImportError("Could not import settings '%s' (Is it on sys.path?): %s" % (self.SETTINGS_MODULE, e))
ImportError: Could not import settings 'openpds.settings' (Is it on sys.path?): cannot import name Connection
(pdsEnv)kitchen@60aa1b8653be:~/pdsEnv/openPDS$
```

Any immediate thoughts?

**Comment by fjqdxq** [comment]
hi,do you have  a solution? I have the same problem, 
 thanks

**Comment by patcon** [comment]
No sorry @fjqdxq, never figured it out :(

**Comment by brian717** [comment]
Just checking - did you run through all of the steps in the readme? In particular, have you run:
    pip install -r requirements.txt

**Comment by khaled-riad** [comment]
Hello, I have the same problem, do you solved it?
Thanks

**Comment by deepsidhu1313** [comment]
Hi , same problem here too. 

```
 python manage.py syncdb
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/user/Study/Projects/SnP/pdsEnv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/home/user/Study/Projects/SnP/pdsEnv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/user/Study/Projects/SnP/pdsEnv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 261, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/user/Study/Projects/SnP/pdsEnv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 69, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/home/user/Study/Projects/SnP/pdsEnv/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/user/Study/Projects/SnP/pdsEnv/local/lib/python2.7/site-packages/django/core/management/commands/syncdb.py", line 8, in <module>
    from django.core.management.sql import custom_sql_for_model, emit_post_sync_signal
  File "/home/user/Study/Projects/SnP/pdsEnv/local/lib/python2.7/site-packages/django/core/management/sql.py", line 6, in <module>
    from django.db import models
  File "/home/user/Study/Projects/SnP/pdsEnv/local/lib/python2.7/site-packages/django/db/__init__.py", line 11, in <module>
    if DEFAULT_DB_ALIAS not in settings.DATABASES:
  File "/home/user/Study/Projects/SnP/pdsEnv/local/lib/python2.7/site-packages/django/utils/functional.py", line 184, in inner
    self._setup()
  File "/home/user/Study/Projects/SnP/pdsEnv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/user/Study/Projects/SnP/pdsEnv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 95, in __init__
    raise ImportError("Could not import settings '%s' (Is it on sys.path?): %s" % (self.SETTINGS_MODULE, e))
ImportError: Could not import settings 'openpds.settings' (Is it on sys.path?): cannot import name Connection

```

**Comment by sconrod-tester** [comment]
Hi I am experiencing same issue as above

**Comment by brian717** [comment]
This seems like a different issue than the one reported here. It seems that authentication for the database you're using is failing here. Have you checked to make sure you've provided the correct credentials for accessing your backing database?

**Comment by patcon** [comment]
Looks like you might want to repost in the project issue queue :)
https://github.com/ASKBOT/askbot-devel

Unfortunately this isn't the place to debug (there are others interested in this issue, who are getting notified).

**Comment by brian717** [comment]
@patcon: right, I just realized that the provided stack trace is for a different project entirely. 

@sconrod-tester: The link @patcon provided is a better place to ask this question. This issue tracker is for the openPDS project, not askbot.

**Comment by voodoodrul** [comment]
Same issue here, no resolution found. I'm not terribly familiar with django settings, but it seems the manage script can't resolve pdsEnv/openPDS/openpds/settings.py

**Comment by voodoodrul** [comment]
@brian717 would be it possible to update the README to address the bootstrapping issue? No matter what I try, "openpds.settings" won't resolve on any Ubuntu installation I try. 

`    raise ImportError("Could not import settings '%s' (Is it on sys.path?): %s" % (self.SETTINGS_MODULE, e))
ImportError: Could not import settings 'openpds.settings' (Is it on sys.path?): cannot import name Connection
`

**Comment by patcon** [comment]
I'm a little bit more familiar with django than when I originally posted this: try copying the template at `openpds/settings.py.template` to `openpds/settings.py`, and skimming through to set up obvious config? (Sorry, haven't touched this project in a long time, but saw your message just now.)

**Comment by patcon** [comment]
on a lark, tried to get it going for you using sqlite3. this got me past syncdb:
https://github.com/HumanDynamics/openPDS/pull/49

(I still had to tweak settings.py so that the sqlite db was in a path that already existed :/

but then it seems that more mongo-related things are baked in when I tried to execute `runserver`

**Comment by voodoodrul** [comment]
@patcon Many thanks for the help! I think the issue is that `from pymongo import Connection` is deprecated, but using an older version of pymongo==2.7.2 seems to work fine for me. I made a pull request to update the requirements.txt. All seems to be good for me with that one change.
